### ISSUE TITLE
I  want to know how to analyze the result

### ISSUE THREAD

**Issue by zsgchinese** [mgaillard/PxzBenchmark#1]
i get the result but don't know how to judge the cpu .i don't know the meaning of the numbers in the result.csv

**Comment by mgaillard** [comment]
The result.csv file contains on each line: real time, user time and system time of each execution of PXZ. These times are coming from the /usr/bin/time program and if you want more explanations about their meanings you can read this topic : http://stackoverflow.com/questions/556405/what-do-real-user-and-sys-mean-in-the-output-of-time1

If you want to analyse the results, you can open the file in a spreadsheet and calculate the mean and the standard deviation of each column. Then you will be able to compare these numbers to other computers.

This benchmark was designed to compare the CPU performance of Docker with native system. You can run the same benchmark without Docker and compare the execution times. Actually, in my case the difference was less than 1 %. The conclusion was that the native system and Docker have the same CPU performances.
